version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '13:00'
    open-pull-requests-limit: 10
    allow:
      - dependency-type: direct
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-patch']
    commit-message:
      prefix: 'fix: '
    groups:
      openmeteo:
        patterns:
          - '*'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: weekly
      time: '10:00'
    commit-message:
      prefix: 'fix: '
